name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        server-id: github # This should match the <id> in your pom.xml's distributionManagement
        # settings-path is not strictly necessary here if setup-java's default works
        # but if you keep it, ensure the deploy step knows where it is or let Maven find it by default.
        # For simplicity, let's try without explicitly setting settings-path first,
        # allowing setup-java to use its default location (~/.m2/settings.xml within the runner).

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      # Let Maven use the settings.xml configured by setup-java in the default location
      # The GITHUB_TOKEN is automatically used by setup-java when server-id is 'github'
      run: mvn -B deploy --file pom.xml
      # No explicit -s or env GITHUB_TOKEN needed here for this common setup
