name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # This permission is correctly set

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        server-id: github # Matches the <id> in your pom.xml and settings.xml

    # Your debug step to display settings.xml can remain if you find it useful
    - name: Display settings.xml
      run: |
        echo "Looking for settings.xml at ~/.m2/settings.xml"
        cat ~/.m2/settings.xml || echo "settings.xml not found at ~/.m2/settings.xml"
      continue-on-error: true

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn -B deploy --file pom.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Crucial: Make GITHUB_TOKEN available to Maven
